"""Custom exceptions for validation errors in the Aspirabot application.

Where possible :
Do not retrieve the contents of variables or display the contents of strings;
-> It will prevent the leakage of sensitive or personal information
-> Ensure that error reports and the application log are anonymized.

This module re-exports every exception class from shared/exceptions/*.py
so existing `from shared.exception_util import X` call sites keep working
unchanged after the split into smaller per-domain modules.
"""

# -----------------------------------------------------------------------------
# Imports
# -----------------------------------------------------------------------------

from shared.exceptions.base_error import AspirabotBaseError
from shared.exceptions.browser_errors import (
    BrowserAlreadyLaunchedError,
    BrowserLaunchFailedError,
    BrowserNotLaunchedError,
    CountHtmlElementsConditionNotMetError,
    CountHtmlImagesConditionNotMetError,
    CurrentPageClosedUnexpectedlyError,
    DnsSolverTimeoutExceededError,
    ElementNotFoundForClickError,
    ImageDownloadFailedError,
    ImageNotDownloadedError,
    ImageWaitTimeoutError,
    NoMatchingImageFoundError,
    PageNotAvailableOrClosedError,
    UnsupportedClickModeError,
    UrlNavigationMismatchError,
)
from shared.exceptions.config_errors import (
    ChromiumInstallationFailedError,
    ConfigurationNotLoadedError,
    FailedToCreateRequiredDirectoriesDuringRuntimeError,
    FailedToInitializeLoggingDuringRuntimeError,
    FailedToLoadConfigurationDuringRuntimeError,
    InvalidBrowserEngineError,
    InvalidFolderLogsError,
    InvalidFolderScenariosError,
    InvalidFolderScrapingError,
    InvalidGuiBootingPositionError,
    InvalidGuiBootingSizeError,
    InvalidLogLevelError,
    LoggingNotInitializedError,
    UnsupportedBrowserEngineError,
    UnsupportedOperatingSystemError,
)
from shared.exceptions.discover_errors import (
    ColumnNotFoundError,
    DiscoverComputeError,
    DiscoverFilePatternRequiredError,
    DiscoverFolderNotFoundError,
    DiscoverFolderPathRequiredError,
    DiscoverHubReadError,
    DiscoverKeyMappingRequiredError,
    DiscoverUrlPatternRequiredError,
    DuplicateColumnKeyError,
    InvalidAggregatorsListError,
    InvalidDataUriFormatError,
    UrlPageCheckMismatchError,
)
from shared.exceptions.registry_errors import (
    ExecutorNotRegisteredError,
    FormNotRegisteredError,
    InvalidDurationError,
    InvalidTimeUnitError,
    NoExecutorsRegisteredError,
    OpenUrlTooManyRetriesError,
    ParamsBuilderNotRegisteredError,
)
from shared.exceptions.repository_errors import (
    CsvColumnDuplicateError,
    CsvColumnNotFoundError,
    CsvFileAlreadyExistsError,
    CsvFileNotFoundError,
    CsvFileRepositoryError,
    CsvRowIndexNotFoundError,
    CsvRowNotFoundError,
    JsonFileRepositoryError,
    RepositoryWriteError,
)
from shared.exceptions.scenario_profile_errors import (
    EmptyScenarioIdError,
    ExportFolderNotADirectoryError,
    InvalidDirectoryPathError,
    InvalidFilePathError,
    InvalidProfilesFolderPathError,
    InvalidScenarioJsonContentError,
    InvalidScenariosFolderPathError,
    LogFolderNotADirectoryError,
    ProfileDataMissingError,
    ProfileNotFoundError,
    ScenarioDataMissingError,
    ScenarioNotFoundError,
)
from shared.exceptions.step_execution_errors import (
    DownloadNotDetectedError,
    EmptyCustomUrlError,
    ExportFolderNotConfiguredError,
    InsufficientDataQualityError,
    InvalidJsExtractedValueTypeError,
    JsExtractedPrimaryKeyMissingError,
    MissingUrlFilterError,
    NoDataToExportError,
    ScriptExecutionFailedError,
    SelectorNoElementFoundError,
    UnexpectedProcessResultError,
)
from shared.exceptions.url_source_errors import (
    InvalidUrlSourceValueTypeError,
    UnknownPriorityTypeUsedError,
    UnknownUrlSourceTypeError,
    UrlSourceExhaustedError,
    UrlSourceFileNotFoundError,
    UrlSourceFilesNotDiscoveredError,
    UrlSourceLauncherNotInitializedError,
    UrlSourceNotReadyError,
    UrlSourceNoUrlBufferedError,
)
from shared.exceptions.validation_errors import (
    BlankStringError,
    CallbackNotDefinedError,
    DuplicateItemError,
    EmptyStringError,
    InvalidBooleanError,
    InvalidLruCacheCapacityError,
    InvalidRangeNumbersError,
    LazyAttributeNotFoundError,
    ListEmptyError,
    ListTooLongError,
    StringTooLongError,
    StringTooShortError,
    ValueMustBeNonNegativeError,
    ValueMustBePositiveAndEvenError,
    ValueMustBePositiveError,
    ValueTooLargeError,
    ValueTooSmallError,
)
from shared.exceptions.youtube_errors import (
    YoutubeLanguageMismatchError,
    YoutubeOutputDirParameterEmptyError,
    YoutubeSubtitlesDownloadedError,
    YoutubeSubtitlesNotFoundInMetadataError,
    YoutubeUrlParameterEmptyError,
    YoutubeVideoDataIncompleteError,
)

__all__ = [
    "AspirabotBaseError",
    "BlankStringError",
    "BrowserAlreadyLaunchedError",
    "BrowserLaunchFailedError",
    "BrowserNotLaunchedError",
    "CallbackNotDefinedError",
    "ChromiumInstallationFailedError",
    "ColumnNotFoundError",
    "ConfigurationNotLoadedError",
    "CountHtmlElementsConditionNotMetError",
    "CountHtmlImagesConditionNotMetError",
    "CsvColumnDuplicateError",
    "CsvColumnNotFoundError",
    "CsvFileAlreadyExistsError",
    "CsvFileNotFoundError",
    "CsvFileRepositoryError",
    "CsvRowIndexNotFoundError",
    "CsvRowNotFoundError",
    "CurrentPageClosedUnexpectedlyError",
    "DiscoverComputeError",
    "DiscoverFilePatternRequiredError",
    "DiscoverFolderNotFoundError",
    "DiscoverFolderPathRequiredError",
    "DiscoverHubReadError",
    "DiscoverKeyMappingRequiredError",
    "DiscoverUrlPatternRequiredError",
    "DnsSolverTimeoutExceededError",
    "DownloadNotDetectedError",
    "DuplicateColumnKeyError",
    "DuplicateItemError",
    "ElementNotFoundForClickError",
    "EmptyCustomUrlError",
    "EmptyScenarioIdError",
    "EmptyStringError",
    "ExecutorNotRegisteredError",
    "ExportFolderNotADirectoryError",
    "ExportFolderNotConfiguredError",
    "FailedToCreateRequiredDirectoriesDuringRuntimeError",
    "FailedToInitializeLoggingDuringRuntimeError",
    "FailedToLoadConfigurationDuringRuntimeError",
    "FormNotRegisteredError",
    "ImageDownloadFailedError",
    "ImageNotDownloadedError",
    "ImageWaitTimeoutError",
    "InsufficientDataQualityError",
    "InvalidAggregatorsListError",
    "InvalidBooleanError",
    "InvalidBrowserEngineError",
    "InvalidDataUriFormatError",
    "InvalidDirectoryPathError",
    "InvalidDurationError",
    "InvalidFilePathError",
    "InvalidFolderLogsError",
    "InvalidFolderScenariosError",
    "InvalidFolderScrapingError",
    "InvalidGuiBootingPositionError",
    "InvalidGuiBootingSizeError",
    "InvalidJsExtractedValueTypeError",
    "InvalidLogLevelError",
    "InvalidLruCacheCapacityError",
    "InvalidProfilesFolderPathError",
    "InvalidRangeNumbersError",
    "InvalidScenarioJsonContentError",
    "InvalidScenariosFolderPathError",
    "InvalidTimeUnitError",
    "InvalidUrlSourceValueTypeError",
    "JsExtractedPrimaryKeyMissingError",
    "JsonFileRepositoryError",
    "LazyAttributeNotFoundError",
    "ListEmptyError",
    "ListTooLongError",
    "LogFolderNotADirectoryError",
    "LoggingNotInitializedError",
    "MissingUrlFilterError",
    "NoDataToExportError",
    "NoExecutorsRegisteredError",
    "NoMatchingImageFoundError",
    "OpenUrlTooManyRetriesError",
    "PageNotAvailableOrClosedError",
    "ParamsBuilderNotRegisteredError",
    "ProfileDataMissingError",
    "ProfileNotFoundError",
    "RepositoryWriteError",
    "ScenarioDataMissingError",
    "ScenarioNotFoundError",
    "ScriptExecutionFailedError",
    "SelectorNoElementFoundError",
    "StringTooLongError",
    "StringTooShortError",
    "UnexpectedProcessResultError",
    "UnknownPriorityTypeUsedError",
    "UnknownUrlSourceTypeError",
    "UnsupportedBrowserEngineError",
    "UnsupportedClickModeError",
    "UnsupportedOperatingSystemError",
    "UrlNavigationMismatchError",
    "UrlPageCheckMismatchError",
    "UrlSourceExhaustedError",
    "UrlSourceFileNotFoundError",
    "UrlSourceFilesNotDiscoveredError",
    "UrlSourceLauncherNotInitializedError",
    "UrlSourceNoUrlBufferedError",
    "UrlSourceNotReadyError",
    "ValueMustBeNonNegativeError",
    "ValueMustBePositiveAndEvenError",
    "ValueMustBePositiveError",
    "ValueTooLargeError",
    "ValueTooSmallError",
    "YoutubeLanguageMismatchError",
    "YoutubeOutputDirParameterEmptyError",
    "YoutubeSubtitlesDownloadedError",
    "YoutubeSubtitlesNotFoundInMetadataError",
    "YoutubeUrlParameterEmptyError",
    "YoutubeVideoDataIncompleteError",
]


# EOF
