# -----------------------------------------------------------------------------
# Imports
# -----------------------------------------------------------------------------

from enum import Enum


class StepTypeEnum(Enum):
    """Enumerates all supported scraping step types.

    Each member maps to a distinct browser or scraping action.
    """

    E_UNSET = "UNSET"
    E_SECTION_STEPS = "SECTION_STEPS"
    E_OPEN_URL = "OPEN_URL"
    E_CLOSE_TABS = "CLOSE_TABS"
    E_REFRESH_PAGE = "REFRESH_PAGE"
    E_WAIT_PAGE_STATE = "WAIT_STATE_PAGE"
    E_WAIT_FIXED_TIME = "WAIT_FIXED_TIME"
    E_WAIT_USER_ACTION = "WAIT_USER_ACTION"
    E_COUNT_HTML_ELEMENTS = "COUNT_HTML_ELEMENTS"
    E_COUNT_HTML_IMAGES = "COUNT_HTML_IMAGES"
    E_WAIT_HTML_ELEMENTS = "WAIT_HTML_ELEMENTS"
    E_WAIT_HTML_IMAGES = "WAIT_HTML_IMAGES"
    E_CLICK_ON_ELEMENT = "CLICK_ON_ELEMENT"
    E_CLICK_FOR_DOWNLOAD = "CLICK_FOR_DOWNLOAD"
    E_DOWNLOAD_IMAGE = "DOWNLOAD_IMAGE"
    E_YOUTUBE_SUBTITLES = "YOUTUBE_SUBTITLES"
    E_YOUTUBE_EXTRACT_INFOS = "YOUTUBE_EXTRACT_INFOS"
    E_EXTRACT_TEXTS = "EXTRACT_TEXTS"
    E_EXTRACT_LINKS = "EXTRACT_LINKS"
    E_EXTRACT_VARIABLE = "EXTRACT_VARIABLE"
    E_EXPORT_DATA_TO_CSV = "EXPORT_DATA_TO_CSV"
    E_JUMP_TO_STEP = "JUMP_TO_STEP"
    E_SCROLL_DOWN = "SCROLL_DOWN"
    E_KILL_BROWSER = "KILL_BROWSER"
    E_CHECK_URL_PAGE = "CHECK_URL_PAGE"
    E_RESTART_TO_BEGINNING = "RESTART_TO_BEGINNING"
    E_UNKNOWN = "UNKNOWN"


# EOF
